name: smartcare
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons:
  device_preview:
  flutter_native_splash:
  flutter_svg:  
  dio:
  dartz:
  get_it:
  bloc:
  flutter_bloc:
  logger:
  hive:
  hive_flutter:
  shared_preferences:
  cached_network_image:
  skeletonizer:
  intl:
 
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  hive_generator:  
  build_runner:  

flutter:
  uses-material-design: true

  # assets:
    # - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf

# flutter run --flavor development --target lib/main_development.dart
# flutter run --flavor production --target lib/main_production.dart
