// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCy0g-0BsUVjao_u9-uer0ZKDkSanvhmmc',
    appId: '1:536205315038:web:8e92f01149accad03fab4f',
    messagingSenderId: '536205315038',
    projectId: 'smartcare-app-b9203',
    authDomain: 'smartcare-app-b9203.firebaseapp.com',
    storageBucket: 'smartcare-app-b9203.firebasestorage.app',
    measurementId: 'G-158P5MRJBX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCa_hb3PFQiYPLI5xJmKEvad7-99uFlDfA',
    appId: '1:536205315038:android:a3c9fa18c8e213623fab4f',
    messagingSenderId: '536205315038',
    projectId: 'smartcare-app-b9203',
    storageBucket: 'smartcare-app-b9203.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBe1pn1eM5QjaoG3tDEqnFxjyIuV4PYAPg',
    appId: '1:536205315038:ios:2eb810aeda1aac823fab4f',
    messagingSenderId: '536205315038',
    projectId: 'smartcare-app-b9203',
    storageBucket: 'smartcare-app-b9203.firebasestorage.app',
    iosBundleId: 'com.graduation.smartcare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBe1pn1eM5QjaoG3tDEqnFxjyIuV4PYAPg',
    appId: '1:536205315038:ios:2eb810aeda1aac823fab4f',
    messagingSenderId: '536205315038',
    projectId: 'smartcare-app-b9203',
    storageBucket: 'smartcare-app-b9203.firebasestorage.app',
    iosBundleId: 'com.graduation.smartcare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCy0g-0BsUVjao_u9-uer0ZKDkSanvhmmc',
    appId: '1:536205315038:web:bc759838bc12aaf63fab4f',
    messagingSenderId: '536205315038',
    projectId: 'smartcare-app-b9203',
    authDomain: 'smartcare-app-b9203.firebaseapp.com',
    storageBucket: 'smartcare-app-b9203.firebasestorage.app',
    measurementId: 'G-FETCNWR4GN',
  );
}
